spring:
  application:
    name: patient-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5437/patientdb
    username: farma
    password: farma
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
  rabbitmq:
    host: localhost
    port: 5673
    username: farma
    password: farma

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET:alterar-este-segredo-para-producao-uma-chave-longa}

services:
  medication:
    url: ${MEDICATION_SERVICE_URL:http://localhost:8080}
