spring:
  application:
    name: patient-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://postgres-patient:5432/patientdb
    username: farma
    password: farma
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: farma
    password: farma

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secret: ${JWT_SECRET:LEfkgCqlkkpypMzMpM6MJWbBfAnpg8lHLGNkjHb6ZOSHUGoL/L+RCID13x2Z7QjX}

services:
  medication:
    url: ${MEDICATION_SERVICE_URL:http://medication-service:8080}
  adherence:
    url: ${ADHERENCE_SERVICE_URL:http://adherence-service:8084}
