spring:
  application:
    name: medication-service
  datasource:
    url: jdbc:postgresql://postgres-medication:5432/medicationdb
    username: farma
    password: farma
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: farma
    password: farma

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8080
