spring:
  application:
    name: medication-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://postgres-medication:5432/medicationdb
    username: farma
    password: farma
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: farma
    password: farma

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secret: ${JWT_SECRET:LEfkgCqlkkpypMzMpM6MJWbBfAnpg8lHLGNkjHb6ZOSHUGoL/L+RCID13x2Z7QjX}

jobs:
  receita-perto-vencer:
    cron: ${RECEITA_PERTO_VENCER_CRON:0 0 8 * * *}
    zone: ${RECEITA_PERTO_VENCER_ZONE:America/Sao_Paulo}
    dias-antecedencia: ${RECEITA_PERTO_VENCER_DIAS:7}

services:
  safety:
    url: ${SAFETY_SERVICE_URL:http://safety-service:8081}

logging:
  level:
    org.springframework.security: DEBUG
    io.jsonwebtoken: DEBUG
