spring:
  application:
    name: safety-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://postgres-safety:5432/safetydb
    username: farma
    password: farma
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: farma
    password: farma
    messaging:
      exchange:
        events: ${RABBITMQ_EXCHANGE_EVENTS:farma.events}
      queue:
        medication-created: ${RABBITMQ_QUEUE_MEDICATION_CREATED:safety.medication.created}
        medication-created-dlq: ${RABBITMQ_QUEUE_MEDICATION_CREATED_DLQ:safety.medication.created.dlq}
      routing:
        medication-created: ${RABBITMQ_ROUTING_MEDICATION_CREATED:medication.created}
        medication-created-dlq: ${RABBITMQ_ROUTING_MEDICATION_CREATED_DLQ:safety.medication.created.dlq}
        safety-alert-created: ${RABBITMQ_ROUTING_SAFETY_ALERT_CREATED:safety.alert.created}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET}
