spring:
  application:
    name: safety-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5436/safetydb
    username: farma
    password: farma
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: America/Sao_Paulo
  rabbitmq:
    host: localhost
    port: 5673
    username: farma
    password: farma

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:LEfkgCqlkkpypMzMpM6MJWbBfAnpg8lHLGNkjHb6ZOSHUGoL/L+RCID13x2Z7QjX}
